### ISSUE TITLE
(How to?) Disable Tag Theming

### ISSUE THREAD

**Issue by ianelletson** [yoyurec/logseq-awesome-styler#68]
Please provide the option or indicate how to disable the custom tag styling.
The current tag styling is a dealbreaker for me. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1207114/205448577-def35b90-39a2-46e8-a10e-621a809810ca.png)

Thank you for your many valuable contributions.

**Comment by yoyurec** [comment]
you mean bg coloring?
not sure it's easy to update plugin code, so try own `custom.css`
```css
#app-container .tag {
    color: var(--ls-primary-text-color) !important;
    background-color: transparent !important;
}
```
