### ISSUE TITLE
Dracula preset

### ISSUE THREAD

**Issue by szjani** [yoyurec/logseq-awesome-styler#82]
**Idea**
I have created a Dracula preset. I'm wondering if you are interested in adding it as a built-in preset.
Some changes were also added to the `custom.css` file.

```css
#today-queries > div.lazy-visibility { border-radius: 4px; background: #323341; counter-reset: list-number;}
#today-queries > div.lazy-visibility div.fade-enter > div.ls-block { background: #44475a; margin: 10px; border-radius: 4px; padding-left: 30px; }
#today-queries > div.lazy-visibility div.fade-enter > div.ls-block:before {counter-increment: list-number; content: counter(list-number); margin-left: 10px; color: #6272a4; position: absolute; left: 0px;}
div.admonitionblock.important {border: 1px solid #bf525b; border-radius: 4px; padding: 10px; background: #332936; margin: 4px; }
div.admonitionblock.important .admonition-icon { border-right-color: #bf525b; }
div.admonitionblock.caution {border: 1px solid #df951d; border-radius: 4px; padding: 10px; background: #363029; margin: 4px; }
div.admonitionblock.caution .admonition-icon { border-right-color: #df951d; }
div.admonitionblock.warning {border: 1px solid #df951d; border-radius: 4px; padding: 10px; background: #363029; margin: 4px; }
div.admonitionblock.warning .admonition-icon { border-right-color: #df951d; }
div.admonitionblock.tip {border: 1px solid #4e82cd; border-radius: 4px; padding: 10px; background: #292f36; margin: 4px; }
div.admonitionblock.tip .admonition-icon { border-right-color: #4e82cd; }
div.admonitionblock.note {border: 1px solid #4e82cd; border-radius: 4px; padding: 10px; background: #292f36; margin: 4px; }
div.admonitionblock.note .admonition-icon { border-right-color: #4e82cd; }
div.admonitionblock.pinned {border: 1px solid #bf525b; border-radius: 4px; padding: 10px; background: #363029; margin: 4px; }
div.admonitionblock.pinned .admonition-icon { border-right-color: #bf525b; }
.ls-wide-mode .cp__sidebar-main-content>div {margin-left: 20px; margin-right: 20px; margin-top: 20px;}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/545872/223384120-7cd976fb-ae25-49cc-a320-adceeab5a7ff.png)
![Névtelen](https://user-images.githubusercontent.com/545872/223385474-85ec8e64-477f-47d1-9fc1-52b4c2732c0f.png)
![image](https://user-images.githubusercontent.com/545872/223386435-d6afd7f9-dbb2-41b4-bc66-da7d03096270.png)

**Comment by yoyurec** [comment]
nice... need to think... i've started to port Dracula twice ))

do you have a light version too? )

**Comment by szjani** [comment]
I'm not aware of a light version of Dracula :)
Found this though, it could be the one: https://marketplace.visualstudio.com/items?itemName=ashrafhadden.dracula-dot-min

**Comment by szjani** [comment]
I have created a light version, also did some changes on the dark one:

![image](https://user-images.githubusercontent.com/545872/224417779-c1cac176-fa2c-4693-b2a4-6bc18401f21b.png)
![image](https://user-images.githubusercontent.com/545872/224417981-0101eec0-d67c-43a2-bc73-fcc5f2f5ca5b.png)

custom.css:

```css
#today-queries > div.lazy-visibility { border-radius: 4px; counter-reset: list-number;}
#today-queries div.custom-query {background: var(--ls-block-properties-background-color);}
#today-queries > div.lazy-visibility div.fade-enter > div.ls-block { background: var(--awSt-ui-body-bg-user); margin: 10px; border-radius: 4px; padding-left: 30px; }
#today-queries > div.lazy-visibility div.fade-enter > div.ls-block:before {counter-increment: list-number; content: counter(list-number); margin-left: 10px; color: #6272a4; position: absolute; left: 0px;}
#today-queries>.lazy-visibility+.lazy-visibility {margin-left: 0px;}
div.admonitionblock.important {border: 1px solid #bf525b; border-radius: 4px; padding: 10px;  margin: 4px; }
div.admonitionblock.important .admonition-icon { border-right-color: #bf525b; }
div.admonitionblock.caution {border: 1px solid #df951d; border-radius: 4px; padding: 10px; margin: 4px; }
div.admonitionblock.caution .admonition-icon { border-right-color: #df951d; }
div.admonitionblock.warning {border: 1px solid #df951d; border-radius: 4px; padding: 10px; margin: 4px; }
div.admonitionblock.warning .admonition-icon { border-right-color: #df951d; }
div.admonitionblock.tip {border: 1px solid #4e82cd; border-radius: 4px; padding: 10px; margin: 4px; }
div.admonitionblock.tip .admonition-icon { border-right-color: #4e82cd; }
div.admonitionblock.note {border: 1px solid #4e82cd; border-radius: 4px; padding: 10px; margin: 4px; }
div.admonitionblock.note .admonition-icon { border-right-color: #4e82cd; }
div.admonitionblock.pinned {border: 1px solid #bf525b; border-radius: 4px; padding: 10px; margin: 4px; }
div.admonitionblock.pinned .admonition-icon { border-right-color: #bf525b; }
```
